spring.application.name=shopping_mall
spring.datasource.url=jdbc:postgresql://localhost:5432/shoppingmall
spring.datasource.username=postgres
spring.datasource.password=hariram007@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

